module.exports = {
    "andamanandnicobarislands":"AN",
    "andhrapradesh": "AP",
    "arunachalpradesh": "AR",
    "assam": "AS",
    "bihar": "BR",
    "chandigarh": "CH",
    "chhattisgarh": "CT",
    "dadraandnagarhaveli": "DN",
    "damananddiu": "DD",
    "delhi": "DL",
    "goa": "GA",
    "gujarat": "GJ",
    "haryana": "HR",
    "himachalpradesh": "HP",
    "jammuandkashmir": "JK",
    "jharkhand": "JH",
    "karnataka": "KA",
    "kerala": "KL",
    "ladakh": "LA",
    "lakshadweep": "LD",
    "madhyapradesh": "MP",
    "maharashtra": "MH",
    "manipur": "MN",
    "meghalaya": "ML",
    "mizoram": "MZ",
    "nagaland": "NL",
    "odisha": "OR",
    "puducherry": "PY",
    "pondicherry": "PY", // MOST PEOPLE STILL USE PONDICHERRY
    "punjab": "PB",
    "rajasthan": "RJ",
    "sikkim": "SK",
    "tamilnadu": "TN",
    "telangana": "TG",
    "tripura": "TR",
    "uttarpradesh": "UP",
    "uttarakhand": "UT",
    "westbengal": "WB",
    "india": "TT",
    "total": "TT",
}
// ACCORDING TO https://api.covid19india.org/data.json